// GlyphAtlas — rasterises font glyphs to a single backing canvas and packs
// them via a simple shelf-packer. Each glyph gets an approximate signed
// distance field generated by a cheap 2-pass Chamfer 3-4 scan so callers can
// resample the atlas at any target size with tolerably smooth edges.
//
// Zero runtime deps. Designed to live alongside Canvas2D rendering today and
// graduate to WebGL sampling later without changing the public API.

/**
 * Letter spacing, in pixels, applied through the canvas where it is supported.
 *
 * `ctx.letterSpacing` is the only way to get tracking that `measureText` also
 * accounts for, which matters more than the drawing: a label measured without
 * its tracking gets a collision box narrower than its ink, and the placer then
 * lets neighbours overlap exactly where the tracking is widest.
 *
 * Returns whether the context took it. Where it did not, callers add
 * `trackingWidth` to the measurement themselves and the text draws untracked -
 * wrong, but wrong in the direction that keeps labels apart rather than piling
 * them on top of each other.
 */
function applyTracking(ctx: CanvasRenderingContext2D, spacing?: number): boolean {
  if (!spacing)
    return true

  if (!('letterSpacing' in ctx))
    return false

  const tracked = ctx as CanvasRenderingContext2D & { letterSpacing: string }
  tracked.letterSpacing = `${spacing}px`

  return true
}

/**
 * The width tracking adds to a run.
 *
 * Canvas puts the spacing after every glyph including the last, which is what
 * the browsers implementing `letterSpacing` do, so the count is the number of
 * code points rather than the gaps between them.
 */
function trackingWidth(text: string, spacing?: number): number {
  if (!spacing)
    return 0

  let count = 0

  for (const _ of text)
    count++

  return count * spacing
}

export interface GlyphMetrics {
  codePoint: number
  /** Atlas-space x of the glyph's top-left. */
  x: number
  /** Atlas-space y of the glyph's top-left. */
  y: number
  /** Packed bitmap width, in atlas pixels. */
  width: number
  /** Packed bitmap height, in atlas pixels. */
  height: number
  /** Horizontal advance to the next glyph, in atlas pixels. */
  advance: number
  /** Left-side bearing, from the pen origin to the bitmap's left edge. */
  bearingX: number
  /** Top-side bearing, from the baseline up to the bitmap's top edge. */
  bearingY: number
}

export interface GlyphAtlasOptions {
  fontFamily?: string
  fontSize?: number
  /** SDF halo radius in pixels; also acts as the pack padding. */
  padding?: number
  /** Initial canvas side; grows by doubling when a shelf can't fit. */
  bucketSize?: number
}

interface StyleKey {
  italic: boolean
  bold: boolean
}

interface GlyphKey {
  codePoint: number
  italic: boolean
  bold: boolean
}

function styleKey(k: StyleKey | undefined): string {
  if (!k)
    return 'r'
  return `${k.italic ? 'i' : 'r'}${k.bold ? 'b' : ''}`
}

function cacheKey(k: GlyphKey): string {
  return `${k.codePoint}:${styleKey(k)}`
}


export class GlyphAtlas {
  canvas: HTMLCanvasElement

  private _ctx: CanvasRenderingContext2D | null
  private _fontFamily: string
  private _fontSize: number
  private _padding: number
  private _glyphs: Map<string, GlyphMetrics>
  // Shelf-packer state.
  private _shelfY: number
  private _shelfX: number
  private _shelfH: number

  constructor(opts?: GlyphAtlasOptions) {
    this._fontFamily = opts?.fontFamily ?? 'system-ui, -apple-system, Segoe UI, Roboto'
    this._fontSize = opts?.fontSize ?? 24
    // 8px of field at a 24px font gives halos room to grow; 4 clipped every
    // halo wider than about a pixel on screen.
    this._padding = opts?.padding ?? 8
    const bucketSize = opts?.bucketSize ?? 512

    this.canvas = document.createElement('canvas')
    this.canvas.width = bucketSize
    this.canvas.height = bucketSize
    this._ctx = this.canvas.getContext('2d')
    this._glyphs = new Map()
    this._shelfX = 0
    this._shelfY = 0
    this._shelfH = 0
  }

  getOrAddGlyph(codePoint: number, style?: { italic?: boolean, bold?: boolean }): GlyphMetrics {
    const key: GlyphKey = {
      codePoint,
      italic: !!style?.italic,
      bold: !!style?.bold,
    }
    const existing = this._glyphs.get(cacheKey(key))
    if (existing)
      return existing

    return this._rasterize(key)
  }

  measure(text: string, style?: { italic?: boolean, bold?: boolean, family?: string }): { width: number, height: number } {
    let width = 0
    let height = 0
    // Walk Unicode code points so surrogate pairs contribute as a single glyph.
    for (const ch of text) {
      const cp = ch.codePointAt(0) ?? 0
      const g = this.getOrAddGlyph(cp, style)
      width += g.advance
      if (g.height > height)
        height = g.height
    }
    return { width, height }
  }

  /**
   * Per-glyph advances at a given text size, walking code points so a
   * surrogate pair counts once.
   *
   * Line placement needs each glyph's own width to step along the geometry;
   * `measure` only reports the total.
   */
  advances(text: string, size: number, style?: { italic?: boolean, bold?: boolean, family?: string, letterSpacing?: number }): Array<{ char: string, advance: number }> {
    const ctx = this._ctx
    const out: Array<{ char: string, advance: number }> = []

    if (ctx) {
      // Measured at the size it will be drawn at, with the same font — so the
      // glyphs a line label steps along land exactly where the text engine
      // will put them. Scaling a 24px advance drifts, and a label a dozen
      // glyphs long drifts visibly.
      ctx.save()
      ctx.font = this.fontString(size, style)
      const tracking = style?.letterSpacing ?? 0

      // Added per glyph rather than set on the context: these are measured one
      // character at a time, and a context that spaces after every glyph would
      // report the tracking on each of them anyway.
      for (const ch of text)
        out.push({ char: ch, advance: ctx.measureText(ch).width + tracking })
      ctx.restore()
      return out
    }

    // No 2D context (a stubbed canvas): fall back to the atlas metrics.
    const scale = size / this._fontSize
    for (const ch of text) {
      const cp = ch.codePointAt(0) ?? 0
      const g = this.getOrAddGlyph(cp, style)
      out.push({ char: ch, advance: g.advance * scale })
    }
    return out
  }

  /**
   * Measure a run at the size it will be drawn at.
   *
   * `measure()` reports atlas units, which the caller then has to scale —
   * an approximation that leaves collision boxes slightly out of step with the
   * ink. This asks the same text engine that will do the drawing.
   */
  measureText(
    text: string,
    size: number,
    style?: { italic?: boolean, bold?: boolean, family?: string, letterSpacing?: number },
  ): { width: number, height: number, ascent: number, descent: number } {
    const ctx = this._ctx
    if (!ctx) {
      const atlas = this.measure(text, style)
      const scale = size / this._fontSize
      const height = atlas.height * scale
      const tracking = trackingWidth(text, style?.letterSpacing)
      return { width: atlas.width * scale + tracking, height, ascent: height * 0.8, descent: height * 0.2 }
    }

    ctx.save()
    ctx.font = this.fontString(size, style)
    const spaced = applyTracking(ctx, style?.letterSpacing)
    const m = ctx.measureText(text)
    // A context that ignores the property still has to report the width the
    // drawing will actually take, or the collision box is too small and
    // labels overlap exactly where tracking is widest.
    const width = spaced ? m.width : m.width + trackingWidth(text, style?.letterSpacing)
    ctx.restore()

    // Font bounding boxes rather than the ink's: a label's box should not
    // change height because its text happens to have no descender.
    const ascent = m.fontBoundingBoxAscent || m.actualBoundingBoxAscent || size * 0.8
    const descent = m.fontBoundingBoxDescent || m.actualBoundingBoxDescent || size * 0.2
    return { width, height: ascent + descent, ascent, descent }
  }

  /**
   * The CSS font string for a style, at a given size.
   *
   * Exposed because line placement draws glyph by glyph and needs to set the
   * same font the measurements were taken with.
   */
  fontString(size: number, style?: { italic?: boolean, bold?: boolean, family?: string }): string {
    const parts: string[] = []
    if (style?.italic)
      parts.push('italic')
    if (style?.bold)
      parts.push('700')
    parts.push(`${size}px`, style?.family || this._fontFamily)
    return parts.join(' ')
  }

  /**
   * Turn a style's `text-font` into a CSS family stack.
   *
   * Style-spec font names carry their weight and slant in the name —
   * "Noto Sans Bold Italic" — because the SDK they were written for looks them
   * up in a glyph server, not in the system's font table. A browser wants a
   * family with the weight applied separately, so the modifiers are stripped
   * and reported back for the caller to apply.
   *
   * The atlas's own stack is appended as a fallback, so a style naming a font
   * the viewer does not have still renders in something sensible.
   */
  resolveFont(textFont: string | string[] | undefined): { family: string, bold: boolean, italic: boolean } {
    const names = Array.isArray(textFont) ? textFont : textFont ? [textFont] : []
    if (!names.length)
      return { family: this._fontFamily, bold: false, italic: false }

    let bold = false
    let italic = false
    const families: string[] = []

    for (const raw of names) {
      if (typeof raw !== 'string' || !raw)
        continue
      let name = raw
      // Longest first: "Semibold" must not be consumed by "Bold".
      for (const [token, apply] of [
        ['Semibold', () => { bold = true }],
        ['Bold', () => { bold = true }],
        ['Italic', () => { italic = true }],
        ['Oblique', () => { italic = true }],
        ['Regular', () => {}],
        ['Medium', () => {}],
        ['Light', () => {}],
      ] as Array<[string, () => void]>) {
        if (name.includes(token)) {
          apply()
          name = name.replace(token, '')
        }
      }
      const cleaned = name.replace(/\s+/g, ' ').trim()
      if (cleaned)
        families.push(cleaned.includes(' ') ? `"${cleaned}"` : cleaned)
    }

    families.push(this._fontFamily)
    return { family: families.join(', '), bold, italic }
  }

  /**
   * Draw a run of text, with an optional halo.
   *
   * This paints through the canvas's own text engine rather than blitting the
   * atlas. The atlas is a signed distance field rasterised at a single size,
   * so every label was a resample of it — upscaled, thresholded and softened,
   * which is what made labels look blurry next to the crisp vector lines
   * beside them. `fillText` renders at the device resolution with real
   * hinting, and `strokeText` gives a halo that follows the glyph outline
   * instead of approximating it.
   *
   * The atlas remains the measurement authority and the WebGL path's texture;
   * this is the Canvas2D path only.
   */
  drawText(
    ctx: CanvasRenderingContext2D,
    text: string,
    x: number,
    y: number,
    options: {
      color: string
      haloColor?: string
      haloWidth?: number
      size: number
      italic?: boolean
      bold?: boolean
      family?: string
      letterSpacing?: number
    },
  ): void {
    const style = { italic: !!options.italic, bold: !!options.bold, family: options.family }

    ctx.save()
    ctx.font = this.fontString(options.size, style)
    applyTracking(ctx, options.letterSpacing)
    ctx.textAlign = 'left'
    ctx.textBaseline = 'alphabetic'

    if (options.haloColor && options.haloWidth && options.haloWidth > 0) {
      ctx.strokeStyle = options.haloColor
      // Doubled because a stroke straddles the outline: half of it lands
      // inside the glyph, where the fill covers it again.
      ctx.lineWidth = options.haloWidth * 2
      ctx.lineJoin = 'round'
      ctx.miterLimit = 2
      ctx.strokeText(text, x, y)
    }

    ctx.fillStyle = options.color
    ctx.fillText(text, x, y)
    ctx.restore()
  }



  // _buildSDF — input is an 8-bit alpha bitmap (`imageData.data[i*4+3]`).
  // Returns a fresh ImageData whose alpha channel encodes a clamped distance
  // field: 0 = far inside, 128 = edge, 255 = far outside. Uses Chamfer 3-4.
  _buildSDF(imageData: ImageData): ImageData {
    const w = imageData.width
    const h = imageData.height
    const radius = this._padding
    const INF = 1 << 20
    // A chamfer transform spreads outward from its zero-valued seeds, so each
    // array measures the distance to the thing it was seeded ON, not the
    // region it is named for: seeding the non-ink pixels with zero yields, at
    // every pixel, the distance to the nearest non-ink pixel — i.e. how deep
    // inside the glyph that pixel is.
    const depthInside = new Int32Array(w * h)
    const distanceToInk = new Int32Array(w * h)

    for (let i = 0; i < w * h; i++) {
      const a = imageData.data[i * 4 + 3]
      if (a >= 128) {
        depthInside[i] = INF
        distanceToInk[i] = 0
      }
      else {
        depthInside[i] = 0
        distanceToInk[i] = INF
      }
    }

    chamfer34(depthInside, w, h)
    chamfer34(distanceToInk, w, h)

    const out = createImageData(w, h)
    for (let i = 0; i < w * h; i++) {
      // Signed distance: positive outside, negative inside. Scale by radius*3
      // (chamfer unit = 3 per pixel) and map to 0..255 with the edge at 128.
      //
      // Subtracting these the other way round inverts the field, which renders
      // as an opaque block with the letters punched out of it — the glyph's
      // background, drawn instead of the glyph.
      const d = (distanceToInk[i] - depthInside[i]) / 3
      let v = 128 - (d / radius) * 128
      if (v < 0)
        v = 0
      else if (v > 255)
        v = 255
      out.data[i * 4 + 0] = 255
      out.data[i * 4 + 1] = 255
      out.data[i * 4 + 2] = 255
      out.data[i * 4 + 3] = v | 0
    }
    return out
  }

  // -------------------------------------------------------------------------
  // Internals
  // -------------------------------------------------------------------------


  private _rasterize(key: GlyphKey): GlyphMetrics {
    const ctx = this._ctx
    // Fallback path for environments without a 2D context (e.g. a harness
    // that stubs <canvas> out): produce an empty glyph with a plausible
    // advance so text layout still proceeds.
    if (!ctx) {
      const metrics: GlyphMetrics = {
        codePoint: key.codePoint,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        advance: this._fontSize * 0.6,
        bearingX: 0,
        bearingY: 0,
      }
      this._glyphs.set(cacheKey(key), metrics)
      return metrics
    }

    const font = this._buildFontSpec(key)
    ctx.font = font

    const ch = String.fromCodePoint(key.codePoint)
    const m = ctx.measureText(ch)
    // Fall back to size-based estimates when the harness returns 0-width
    // metrics (very-happy-dom's text metrics aren't fully populated).
    const advance = (m.width && m.width > 0) ? m.width : this._fontSize * 0.6
    const ascent = (m.actualBoundingBoxAscent && m.actualBoundingBoxAscent > 0)
      ? m.actualBoundingBoxAscent
      : this._fontSize * 0.8
    const descent = (m.actualBoundingBoxDescent && m.actualBoundingBoxDescent > 0)
      ? m.actualBoundingBoxDescent
      : this._fontSize * 0.2

    const pad = this._padding
    const bmpW = Math.max(1, Math.ceil(advance)) + pad * 2
    const bmpH = Math.max(1, Math.ceil(ascent + descent)) + pad * 2

    // Rasterise into a scratch canvas, run SDF, paste into the atlas.
    const scratch = document.createElement('canvas')
    scratch.width = bmpW
    scratch.height = bmpH
    const sctx = scratch.getContext('2d')
    if (sctx) {
      sctx.font = font
      sctx.fillStyle = '#000'
      sctx.textBaseline = 'alphabetic'
      sctx.fillText(ch, pad, pad + ascent)
      // Replace the scratch imageData with its SDF. getImageData can be
      // unreliable in test shims, so guard against throws.
      try {
        const src = sctx.getImageData(0, 0, bmpW, bmpH)
        const sdf = this._buildSDF(src)
        sctx.putImageData(sdf, 0, 0)
      }
      catch {
        // Swallow — fall through with the raw raster.
      }
    }

    // Shelf packer: advance the current shelf first, grow the canvas if
    // neither the current shelf nor a fresh one would fit.
    if (this._shelfX + bmpW > this.canvas.width) {
      this._shelfY += this._shelfH
      this._shelfX = 0
      this._shelfH = 0
    }
    if (this._shelfY + bmpH > this.canvas.height)
      this._growAtlas(Math.max(this.canvas.width * 2, this._shelfY + bmpH))
    if (this._shelfX + bmpW > this.canvas.width)
      this._growAtlas(Math.max(this.canvas.width * 2, this._shelfX + bmpW))

    const dx = this._shelfX
    const dy = this._shelfY
    ctx.drawImage(scratch, dx, dy)
    this._shelfX += bmpW
    if (bmpH > this._shelfH)
      this._shelfH = bmpH

    const metrics: GlyphMetrics = {
      codePoint: key.codePoint,
      x: dx,
      y: dy,
      width: bmpW,
      height: bmpH,
      advance,
      bearingX: -pad,
      bearingY: ascent + pad,
    }
    this._glyphs.set(cacheKey(key), metrics)
    return metrics
  }

  private _buildFontSpec(key: StyleKey): string {
    const parts: string[] = []
    if (key.italic)
      parts.push('italic')
    if (key.bold)
      parts.push('bold')
    parts.push(`${this._fontSize}px`)
    parts.push(this._fontFamily)
    return parts.join(' ')
  }

  private _growAtlas(newSide: number): void {
    const old = this.canvas
    const target = document.createElement('canvas')
    target.width = Math.max(newSide, old.width)
    target.height = Math.max(newSide, old.height)
    const tctx = target.getContext('2d')
    if (tctx)
      tctx.drawImage(old, 0, 0)
    this.canvas = target
    this._ctx = tctx
  }
}

// Build an ImageData-shaped object without depending on the global
// constructor, which isn't populated by every DOM harness (e.g. happy-dom).
// Prefers the real constructor when available so consumers still get a
// structurally correct ImageData at runtime.
function createImageData(width: number, height: number): ImageData {
  const data = new Uint8ClampedArray(width * height * 4)
  const ctor = (globalThis as any).ImageData
  if (typeof ctor === 'function') {
    try {
      return new ctor(data, width, height) as ImageData
    }
    catch {
      // Some environments reject the (data, w, h) overload — fall through.
    }
  }
  return { data, width, height, colorSpace: 'srgb' } as unknown as ImageData
}

// Chamfer 3-4 two-pass distance transform on a flat w*h int32 buffer where
// seed cells are 0 and everything else is a large sentinel.
function chamfer34(buf: Int32Array, w: number, h: number): void {
  // Forward pass.
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = y * w + x
      let v = buf[i]
      if (y > 0) {
        if (x > 0) {
          const c = buf[i - w - 1] + 4
          if (c < v)
            v = c
        }
        const c2 = buf[i - w] + 3
        if (c2 < v)
          v = c2
        if (x < w - 1) {
          const c3 = buf[i - w + 1] + 4
          if (c3 < v)
            v = c3
        }
      }
      if (x > 0) {
        const c4 = buf[i - 1] + 3
        if (c4 < v)
          v = c4
      }
      buf[i] = v
    }
  }
  // Backward pass.
  for (let y = h - 1; y >= 0; y--) {
    for (let x = w - 1; x >= 0; x--) {
      const i = y * w + x
      let v = buf[i]
      if (y < h - 1) {
        if (x < w - 1) {
          const c = buf[i + w + 1] + 4
          if (c < v)
            v = c
        }
        const c2 = buf[i + w] + 3
        if (c2 < v)
          v = c2
        if (x > 0) {
          const c3 = buf[i + w - 1] + 4
          if (c3 < v)
            v = c3
        }
      }
      if (x < w - 1) {
        const c4 = buf[i + 1] + 3
        if (c4 < v)
          v = c4
      }
      buf[i] = v
    }
  }
}
