// GlyphAtlas — rasterises font glyphs to a single backing canvas and packs
// them via a simple shelf-packer. Each glyph gets an approximate signed
// distance field generated by a cheap 2-pass Chamfer 3-4 scan so callers can
// resample the atlas at any target size with tolerably smooth edges.
//
// Zero runtime deps. Designed to live alongside Canvas2D rendering today and
// graduate to WebGL sampling later without changing the public API.

export interface GlyphMetrics {
  codePoint: number
  /** Atlas-space x of the glyph's top-left. */
  x: number
  /** Atlas-space y of the glyph's top-left. */
  y: number
  /** Packed bitmap width, in atlas pixels. */
  width: number
  /** Packed bitmap height, in atlas pixels. */
  height: number
  /** Horizontal advance to the next glyph, in atlas pixels. */
  advance: number
  /** Left-side bearing, from the pen origin to the bitmap's left edge. */
  bearingX: number
  /** Top-side bearing, from the baseline up to the bitmap's top edge. */
  bearingY: number
}

export interface GlyphAtlasOptions {
  fontFamily?: string
  fontSize?: number
  /** SDF halo radius in pixels; also acts as the pack padding. */
  padding?: number
  /** Initial canvas side; grows by doubling when a shelf can't fit. */
  bucketSize?: number
}

interface StyleKey {
  italic: boolean
  bold: boolean
}

interface GlyphKey {
  codePoint: number
  italic: boolean
  bold: boolean
}

function styleKey(k: StyleKey | undefined): string {
  if (!k)
    return 'r'
  return `${k.italic ? 'i' : 'r'}${k.bold ? 'b' : ''}`
}

function cacheKey(k: GlyphKey): string {
  return `${k.codePoint}:${styleKey(k)}`
}

export class GlyphAtlas {
  canvas: HTMLCanvasElement

  private _ctx: CanvasRenderingContext2D | null
  private _fontFamily: string
  private _fontSize: number
  private _padding: number
  private _glyphs: Map<string, GlyphMetrics>
  // Shelf-packer state.
  private _shelfY: number
  private _shelfX: number
  private _shelfH: number

  constructor(opts?: GlyphAtlasOptions) {
    this._fontFamily = opts?.fontFamily ?? 'system-ui, -apple-system, Segoe UI, Roboto'
    this._fontSize = opts?.fontSize ?? 24
    this._padding = opts?.padding ?? 4
    const bucketSize = opts?.bucketSize ?? 512

    this.canvas = document.createElement('canvas')
    this.canvas.width = bucketSize
    this.canvas.height = bucketSize
    this._ctx = this.canvas.getContext('2d')
    this._glyphs = new Map()
    this._shelfX = 0
    this._shelfY = 0
    this._shelfH = 0
  }

  getOrAddGlyph(codePoint: number, style?: { italic?: boolean, bold?: boolean }): GlyphMetrics {
    const key: GlyphKey = {
      codePoint,
      italic: !!style?.italic,
      bold: !!style?.bold,
    }
    const existing = this._glyphs.get(cacheKey(key))
    if (existing)
      return existing

    return this._rasterize(key)
  }

  measure(text: string, style?: { italic?: boolean, bold?: boolean }): { width: number, height: number } {
    let width = 0
    let height = 0
    // Walk Unicode code points so surrogate pairs contribute as a single glyph.
    for (const ch of text) {
      const cp = ch.codePointAt(0) ?? 0
      const g = this.getOrAddGlyph(cp, style)
      width += g.advance
      if (g.height > height)
        height = g.height
    }
    return { width, height }
  }

  drawText(
    ctx: CanvasRenderingContext2D,
    text: string,
    x: number,
    y: number,
    options: {
      color: string
      haloColor?: string
      haloWidth?: number
      size: number
      italic?: boolean
      bold?: boolean
    },
  ): void {
    const style = { italic: !!options.italic, bold: !!options.bold }
    const scale = options.size / this._fontSize

    if (options.haloColor && options.haloWidth && options.haloWidth > 0) {
      // Emulate a halo by stroking each glyph's silhouette underneath the fill.
      // With Canvas2D the cheapest approximation is to draw the atlas bitmap
      // with `destination-over` so the halo never hides the fill.
      ctx.save()
      ctx.globalCompositeOperation = 'destination-over'
      ctx.fillStyle = options.haloColor
      this._drawRun(ctx, text, x, y, scale, style, options.haloWidth)
      ctx.restore()
    }

    ctx.save()
    ctx.fillStyle = options.color
    this._drawRun(ctx, text, x, y, scale, style, 0)
    ctx.restore()
  }

  // _buildSDF — input is an 8-bit alpha bitmap (`imageData.data[i*4+3]`).
  // Returns a fresh ImageData whose alpha channel encodes a clamped distance
  // field: 0 = far inside, 128 = edge, 255 = far outside. Uses Chamfer 3-4.
  _buildSDF(imageData: ImageData): ImageData {
    const w = imageData.width
    const h = imageData.height
    const radius = this._padding
    const INF = 1 << 20
    const inside = new Int32Array(w * h)
    const outside = new Int32Array(w * h)

    // Seed: pixels with alpha >= 128 are "ink", outside = 0 there and inside
    // starts at INF (and vice-versa for ink).
    for (let i = 0; i < w * h; i++) {
      const a = imageData.data[i * 4 + 3]
      if (a >= 128) {
        outside[i] = INF
        inside[i] = 0
      }
      else {
        outside[i] = 0
        inside[i] = INF
      }
    }

    chamfer34(outside, w, h)
    chamfer34(inside, w, h)

    const out = createImageData(w, h)
    for (let i = 0; i < w * h; i++) {
      // Signed distance: positive outside, negative inside. Scale by radius*3
      // (chamfer unit = 3 per pixel) and map to 0..255 with the edge at 128.
      const d = (outside[i] - inside[i]) / 3
      let v = 128 - (d / radius) * 128
      if (v < 0)
        v = 0
      else if (v > 255)
        v = 255
      out.data[i * 4 + 0] = 255
      out.data[i * 4 + 1] = 255
      out.data[i * 4 + 2] = 255
      out.data[i * 4 + 3] = v | 0
    }
    return out
  }

  // -------------------------------------------------------------------------
  // Internals
  // -------------------------------------------------------------------------

  private _drawRun(
    ctx: CanvasRenderingContext2D,
    text: string,
    x: number,
    y: number,
    scale: number,
    style: StyleKey,
    haloInflate: number,
  ): void {
    let pen = x
    for (const ch of text) {
      const cp = ch.codePointAt(0) ?? 0
      const g = this.getOrAddGlyph(cp, style)
      if (g.width > 0 && g.height > 0) {
        const dx = pen + g.bearingX * scale - haloInflate
        const dy = y - g.bearingY * scale - haloInflate
        const dw = g.width * scale + haloInflate * 2
        const dh = g.height * scale + haloInflate * 2
        ctx.drawImage(
          this.canvas,
          g.x,
          g.y,
          g.width,
          g.height,
          dx,
          dy,
          dw,
          dh,
        )
      }
      pen += g.advance * scale
    }
  }

  private _rasterize(key: GlyphKey): GlyphMetrics {
    const ctx = this._ctx
    // Fallback path for environments without a 2D context (e.g. a harness
    // that stubs <canvas> out): produce an empty glyph with a plausible
    // advance so text layout still proceeds.
    if (!ctx) {
      const metrics: GlyphMetrics = {
        codePoint: key.codePoint,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        advance: this._fontSize * 0.6,
        bearingX: 0,
        bearingY: 0,
      }
      this._glyphs.set(cacheKey(key), metrics)
      return metrics
    }

    const font = this._buildFontSpec(key)
    ctx.font = font

    const ch = String.fromCodePoint(key.codePoint)
    const m = ctx.measureText(ch)
    // Fall back to size-based estimates when the harness returns 0-width
    // metrics (very-happy-dom's text metrics aren't fully populated).
    const advance = (m.width && m.width > 0) ? m.width : this._fontSize * 0.6
    const ascent = (m.actualBoundingBoxAscent && m.actualBoundingBoxAscent > 0)
      ? m.actualBoundingBoxAscent
      : this._fontSize * 0.8
    const descent = (m.actualBoundingBoxDescent && m.actualBoundingBoxDescent > 0)
      ? m.actualBoundingBoxDescent
      : this._fontSize * 0.2

    const pad = this._padding
    const bmpW = Math.max(1, Math.ceil(advance)) + pad * 2
    const bmpH = Math.max(1, Math.ceil(ascent + descent)) + pad * 2

    // Rasterise into a scratch canvas, run SDF, paste into the atlas.
    const scratch = document.createElement('canvas')
    scratch.width = bmpW
    scratch.height = bmpH
    const sctx = scratch.getContext('2d')
    if (sctx) {
      sctx.font = font
      sctx.fillStyle = '#000'
      sctx.textBaseline = 'alphabetic'
      sctx.fillText(ch, pad, pad + ascent)
      // Replace the scratch imageData with its SDF. getImageData can be
      // unreliable in test shims, so guard against throws.
      try {
        const src = sctx.getImageData(0, 0, bmpW, bmpH)
        const sdf = this._buildSDF(src)
        sctx.putImageData(sdf, 0, 0)
      }
      catch {
        // Swallow — fall through with the raw raster.
      }
    }

    // Shelf packer: advance the current shelf first, grow the canvas if
    // neither the current shelf nor a fresh one would fit.
    if (this._shelfX + bmpW > this.canvas.width) {
      this._shelfY += this._shelfH
      this._shelfX = 0
      this._shelfH = 0
    }
    if (this._shelfY + bmpH > this.canvas.height)
      this._growAtlas(Math.max(this.canvas.width * 2, this._shelfY + bmpH))
    if (this._shelfX + bmpW > this.canvas.width)
      this._growAtlas(Math.max(this.canvas.width * 2, this._shelfX + bmpW))

    const dx = this._shelfX
    const dy = this._shelfY
    ctx.drawImage(scratch, dx, dy)
    this._shelfX += bmpW
    if (bmpH > this._shelfH)
      this._shelfH = bmpH

    const metrics: GlyphMetrics = {
      codePoint: key.codePoint,
      x: dx,
      y: dy,
      width: bmpW,
      height: bmpH,
      advance,
      bearingX: -pad,
      bearingY: ascent + pad,
    }
    this._glyphs.set(cacheKey(key), metrics)
    return metrics
  }

  private _buildFontSpec(key: StyleKey): string {
    const parts: string[] = []
    if (key.italic)
      parts.push('italic')
    if (key.bold)
      parts.push('bold')
    parts.push(`${this._fontSize}px`)
    parts.push(this._fontFamily)
    return parts.join(' ')
  }

  private _growAtlas(newSide: number): void {
    const old = this.canvas
    const target = document.createElement('canvas')
    target.width = Math.max(newSide, old.width)
    target.height = Math.max(newSide, old.height)
    const tctx = target.getContext('2d')
    if (tctx)
      tctx.drawImage(old, 0, 0)
    this.canvas = target
    this._ctx = tctx
  }
}

// Build an ImageData-shaped object without depending on the global
// constructor, which isn't populated by every DOM harness (e.g. happy-dom).
// Prefers the real constructor when available so consumers still get a
// structurally correct ImageData at runtime.
function createImageData(width: number, height: number): ImageData {
  const data = new Uint8ClampedArray(width * height * 4)
  const ctor = (globalThis as any).ImageData
  if (typeof ctor === 'function') {
    try {
      return new ctor(data, width, height) as ImageData
    }
    catch {
      // Some environments reject the (data, w, h) overload — fall through.
    }
  }
  return { data, width, height, colorSpace: 'srgb' } as unknown as ImageData
}

// Chamfer 3-4 two-pass distance transform on a flat w*h int32 buffer where
// seed cells are 0 and everything else is a large sentinel.
function chamfer34(buf: Int32Array, w: number, h: number): void {
  // Forward pass.
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = y * w + x
      let v = buf[i]
      if (y > 0) {
        if (x > 0) {
          const c = buf[i - w - 1] + 4
          if (c < v)
            v = c
        }
        const c2 = buf[i - w] + 3
        if (c2 < v)
          v = c2
        if (x < w - 1) {
          const c3 = buf[i - w + 1] + 4
          if (c3 < v)
            v = c3
        }
      }
      if (x > 0) {
        const c4 = buf[i - 1] + 3
        if (c4 < v)
          v = c4
      }
      buf[i] = v
    }
  }
  // Backward pass.
  for (let y = h - 1; y >= 0; y--) {
    for (let x = w - 1; x >= 0; x--) {
      const i = y * w + x
      let v = buf[i]
      if (y < h - 1) {
        if (x < w - 1) {
          const c = buf[i + w + 1] + 4
          if (c < v)
            v = c
        }
        const c2 = buf[i + w] + 3
        if (c2 < v)
          v = c2
        if (x > 0) {
          const c3 = buf[i + w - 1] + 4
          if (c3 < v)
            v = c3
        }
      }
      if (x < w - 1) {
        const c4 = buf[i + 1] + 3
        if (c4 < v)
          v = c4
      }
      buf[i] = v
    }
  }
}
