/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsDemo: typeof import('./theme/components/AnalyticsDemo.vue')['default']
    Canada: typeof import('./theme/components/maps/Canada.vue')['default']
    CanadaDemo: typeof import('./theme/components/maps/CanadaDemo.vue')['default']
    DataVisualizationDemo: typeof import('./theme/components/DataVisualizationDemo.vue')['default']
    HeatmapDemo: typeof import('./theme/components/HeatmapDemo.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    HomeSponsors: typeof import('./theme/components/HomeSponsors.vue')['default']
    HomeTeam: typeof import('./theme/components/HomeTeam.vue')['default']
    Iraq: typeof import('./theme/components/maps/Iraq.vue')['default']
    IraqDemo: typeof import('./theme/components/maps/IraqDemo.vue')['default']
    Italy: typeof import('./theme/components/maps/Italy.vue')['default']
    ItalyDemlo: typeof import('./theme/components/maps/ItalyDemlo.vue')['default']
    ItalyDemo: typeof import('./theme/components/maps/ItalyDemo.vue')['default']
    MarkersMapDemo: typeof import('./theme/components/MarkersMapDemo.vue')['default']
    RegionMapDemo: typeof import('./theme/components/RegionMapDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMember: typeof import('./theme/components/TeamMember.vue')['default']
    UnitedStates: typeof import('./theme/components/maps/UnitedStates.vue')['default']
    UnitedStatesDemo: typeof import('./theme/components/maps/UnitedStatesDemo.vue')['default']
    VectorMapDemo: typeof import('./theme/components/VectorMapDemo.vue')['default']
    WorldMap: typeof import('./theme/components/maps/WorldMap.vue')['default']
    WorldMapDemo: typeof import('./theme/components/maps/WorldMapDemo.vue')['default']
  }
}
